### ISSUE TITLE
OpenGSN Integration

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/ethereum-protocol#5]
**Main goal**
To facilitate onboarding of new users, allow calls to an Open Contract function (which `requiresOracle`) from an empty wallet, by integrating with [OpenGSN](https://opengsn.org/).

**Requirements** 
- Expose a simplified OpenGSN-API-wrapper via the `OpenContract` parent class
- Integrate the OpenGSN provider with the frontend
- If possible to do securely, one `OpenContractsPaymaster`  should be responsible for all Open Contracts (on a given chain) to mimize the complexity+cost of an individual Open Contract as much as possible.

**ToDo**
Chronologially, we need to:
- [ ] Clarify Specs for `OpenContractsPaymaster` and `OpenContract`
- [ ] Implement Solidity contracts
- [ ] Adapt open-contracts/client-protocol to use OpenGSN

**Comment by open-contracts** [comment]
Let's add the spec into https://github.com/open-contracts/ethereum-protocol/blob/OpenGSN/OpenGSNSpec.md
